### ISSUE TITLE
Bug in `classifier.to_yaml`

### ISSUE THREAD

**Issue by MarcSerraPeralta** [MarcSerraPeralta/iq_readout#47]
The values stored in the yaml file are numpy arrays and scalars, which make the yaml file look like this:

```
params:
  0:
    angle: !!python/object/apply:numpy.core.multiarray.scalar
    - *id002
    - !!binary |
      5hhndh8x9z8=
    mu_0_x: !!python/object/apply:numpy.core.multiarray.scalar
    - *id002
    - !!binary |
      9bc+tkxZyr8=
    mu_0_y: !!python/object/apply:numpy.core.multiarray.scalar
    - *id002
    - !!binary |
      NgGCd1+Knb8=
```

and it cannot be loaded using `classifier.from_yaml`. Also the goal of being stored in yaml files is that these files should be readable. 

A test must be added to ensure that the classifiers can be correctly stored and loaded using the yaml files.
